version: '3'

services:
  gogs:
    image: gogs/gogs
    ports:
    - 10080:3000
    links:
    - dbgogs
    volumes:
    - ./data:/data


  dbgogs:
    image: postgres:9.6
    volumes:
      - ./postgresql:/var/lib/postgresql
    environment:
     - POSTGRES_USER=gogs
     - POSTGRES_PASSWORD=gogs

